name: Telegram Bot Ping

on:
  schedule:
    - cron: "*/10 * * * *"  # Каждые 10 минут (UTC)
  workflow_dispatch:        # Возможность запустить вручную

jobs:
  ping-telegram:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: pip install requests

    - name: Run ping script
      run: python ping_bot.py
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
